export const GET_STUDYPATHS = "GET_STUDYPATHS";
export const GET_RESOURCES = "GET_RESOURCES";
export const GET_RESOURCE_TYPES = "GET_RESOURCE_TYPES";

export const GET_CAREERS = "GET_CAREERS";
export const ADD_CAREER = "ADD_CAREER";

export const GET_CAREERKEYWORDS = "GET_CAREERKEYWORDS";

export const ADD_CAREER_GOAL = "ADD_CAREER_GOAL";

export const BEGIN_GENERATING_STUDY_PATH = "BEGIN_GENERATING_STUDY_PATH";
export const FINISH_GENERATING_STUDY_PATH = "FINISH_GENERATING_STUDY_PATH";
export const ABORT_GENERATING_STUDY_PATH = "ABORT_GENERATING_STUDY_PATH";

export const GET_ERRORS = "GET_ERRORS";
export const ADD_RESOURCE = "ADD_RESOURCE";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const GET_MESSAGES = "GET_MESSAGES";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
